branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
      - "irc.mozilla.org#fireplace"
    on_success: change
    on_failure: change
language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "mv hearth/media/js/settings_travis.js hearth/media/js/settings_local.js"
  - "nohup node damper.js &"  # start the damper
  - "git clone git://github.com/n1k0/casperjs.git casperjs"
  - "cd casperjs && git checkout 1.0.2 && cd .."  # Use Homebrew's version of casper
script:
  - "cd smokealarm && DISPLAY=:99.0 ../casperjs/bin/casperjs test tests"
