branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
      - "irc.mozilla.org#fireplace"
    on_success: change
    on_failure: change
  email: false
language: node_js
node_js:
  - "0.10"
before_script:
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - "mv src/media/js/settings_travis.js src/media/js/settings_local.js"
  - "npm install -g commonplace@0.4.22"  # Get commonplace up in hurrr
  - "nohup damper &"  # start the damper
  - "git clone git://github.com/n1k0/casperjs.git casperjs"
  - "cd casperjs && git checkout -q tags/1.1-beta3; cd .."
script:
  - "commonplace lint"  # Lint the repo first!
  - "commonplace langpacks"  # Generate langpacks; will catch PO file errors.
  - "CASPERJS_BIN=casperjs/bin/casperjs make test"
